CREATE TABLE hm_porn_vedio_issue (
   ISSUE_INDEX            TEXT          NOT NULL,
   ISSUE_INDEX_DOC_ID     TEXT          NOT NULL,
   ISSUE_CATEGORY         TEXT          NOT NULL,
   ISSUE_DESCRIPTION      TEXT,
   ISSUE_REPORT_TIME      BIGINT,
   ISSUE_STATE            TEXT          NOT NULL,
   VALIDATING_SESSION     TEXT          NOT NULL,
   PRIMARY KEY(ISSUE_INDEX, ISSUE_INDEX_DOC_ID, ISSUE_CATEGORY, VALIDATING_SESSION)
);
