# This is a basic workflow to help you get started with Actions

name: Eye-Of-Anu Project CI Work flow for non master branch

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ issue_* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Extract tag version
        id: tag_version
        run: |
          export EYE_OF_ANU_VERSION=`. version.sh`
          echo "::set-output name=value::$EYE_OF_ANU_VERSION"

      - name: Build	by Maven
        run: mvn -B clean package

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: ${{ steps.tag_version.outputs.value }}-SNAPSHOT
